# file for zed
[default_config]
version = "0.10.1"
assembler = "nasm"
instruction_set = "x86/x86-64"

[default_config.opts]
diagnostics = true
default_diagnostics = false

[[project]]
path = ""
version = "0.10.1"
assembler = "nasm"
instruction_set = "x86/x86-64"

[project.opts]
compiler = "nasm"
compile_flags_txt = [
    "-f",
    "elf64",
]
diagnostics = true
default_diagnostics = false
